name = "ghpr-server"
main = "src/index.ts"
compatibility_date = "2026-03-01"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "ghpr"
database_id = "079f40b8-aa1f-4495-a89a-0d54546c16f1"
